# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/docs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/docs.proto\x12\x04\x64ocs\"\x1e\n\x0b\x44ocsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x03\x44oc\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\",\n\x0c\x44ocsResponse\x12\x1c\n\tdocuments\x18\x01 \x03(\x0b\x32\t.docs.Doc2A\n\x0b\x44ocsService\x12\x32\n\tDocuments\x12\x11.docs.DocsRequest\x1a\x12.docs.DocsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.docs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOCSREQUEST._serialized_start=26
  _DOCSREQUEST._serialized_end=56
  _DOC._serialized_start=58
  _DOC._serialized_end=109
  _DOCSRESPONSE._serialized_start=111
  _DOCSRESPONSE._serialized_end=155
  _DOCSSERVICE._serialized_start=157
  _DOCSSERVICE._serialized_end=222
# @@protoc_insertion_point(module_scope)
