# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import docs_pb2 as proto_dot_docs__pb2


class DocsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Documents = channel.unary_unary(
                '/docs.DocsService/Documents',
                request_serializer=proto_dot_docs__pb2.DocsRequest.SerializeToString,
                response_deserializer=proto_dot_docs__pb2.DocsResponse.FromString,
                )


class DocsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Documents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Documents': grpc.unary_unary_rpc_method_handler(
                    servicer.Documents,
                    request_deserializer=proto_dot_docs__pb2.DocsRequest.FromString,
                    response_serializer=proto_dot_docs__pb2.DocsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docs.DocsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Documents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/docs.DocsService/Documents',
            proto_dot_docs__pb2.DocsRequest.SerializeToString,
            proto_dot_docs__pb2.DocsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
